# ExampleMod tag to use as Blowdryer (Spotless, etc.) settings version, leave empty to disable.
# LOCAL to test local config updates.
gtnh.settings.blowdryerTag = 0.2.2

# Human-readable mod name, available for mcmod.info population.
modName = Dynamic Sword Skills Unofficial

# Case-sensitive identifier string, available for mcmod.info population and used for automatic mixin JSON generation.
# Conventionally lowercase.
# !!! DO NOT CHANGE - must stay 'dynamicswordskills' for world/item id compatibility !!!
modId = dynamicswordskills

# Root package of the mod, used to find various classes in other properties,
# mcmod.info substitution, enabling assertions in run tasks, etc.
# NOTE: must match an existing package directory under src/main/java
modGroup = dynamicswordskills

# Whether to use modGroup as the maven publishing group.
# When false, com.github.GTNewHorizons is used.
useModGroupForPublishing = true

# Updates your build.gradle and settings.gradle automatically whenever an update is available.
autoUpdateBuildScript = false

# Version of Minecraft to target
minecraftVersion = 1.7.10

# Version of Minecraft Forge to target
forgeVersion = 10.13.4.1614

# Specify an MCP channel for dependency deobfuscation and the deobfParams task.
channel = stable

# Specify an MCP mappings version for dependency deobfuscation.
mappingsVersion = 12

# Defines other MCP mappings for dependency deobfuscation.
remoteMappings = https\://raw.githubusercontent.com/MinecraftForge/FML/1.7.10/conf/

# Select a default username for testing your mod.
developmentEnvironmentUserName = Developer

# Enables modern Java syntax support.
enableModernJavaSyntax = jabel

# Enables injecting missing generics into the decompiled source code for a better coding experience.
enableGenericInjection = true

# Generate a class with a String field for the mod version named as defined below.
generateGradleTokenClass = dynamicswordskills.Tags

# Name of the token containing the project's current version to generate/replace.
gradleTokenVersion = VERSION

# [DEPRECATED]
replaceGradleTokenInFile =

# apiPackage
apiPackage =

# Access transformers file
accessTransformersFile =

# Provides setup for Mixins if enabled.
usesMixins = false

# Set to a non-empty string to configure mixins in a separate source set.
separateMixinSourceSet =

# Adds some debug arguments like verbose output and class export.
usesMixinDebug = false

# Specify the location of your implementation of IMixinConfigPlugin.
mixinPlugin =

# Specify the package that contains all of your Mixins.
mixinsPackage = mixin

# Specify the core mod entry class if you use a core mod.
coreModClass =

# If your project is only a consolidation of mixins or a core mod.
containsMixinsAndOrCoreModOnly = false

# Enables Mixins even if this mod doesn't use them.
forceEnableMixins = false

# If enabled, you may use 'shadowCompile' for dependencies.
usesShadowedDependencies = false

# If disabled, won't remove unused classes from shadowed dependencies.
minimizeShadowedDependencies = true

# If disabled, won't rename the shadowed classes.
relocateShadowedDependencies = true

# Adds CurseMaven, Modrinth, and some more well-known 1.7.10 repositories.
includeWellKnownRepositories = true

# A list of repositories to exclude from the includeWellKnownRepositories setting.
excludeWellKnownRepositories =

# Change these to your Maven coordinates if you want to publish to a custom Maven repository.
usesMavenPublishing = true

# Maven repository to publish the mod to.
# mavenPublishUrl =

# Publishing to Modrinth
modrinthProjectId =

# The project's relations on Modrinth.
modrinthRelations =

# Publishing to CurseForge
curseForgeProjectId =

# The project's relations on CurseForge.
curseForgeRelations =

# Optional parameter to customize the produced artifacts.
customArchiveBaseName = DynamicSwordSkillsUnofficial-MC1.7.10

# Optional parameter to customize the default working directory used by the runClient* tasks.
# runClientWorkingDirectory = run/client

# Optional parameter to customize the default working directory used by the runServer* tasks.
# runServerWorkingDirectory = run/server

# Optional parameter to have the build automatically fail if an illegal version is used.
# versionPattern =

# Uncomment to prevent the source code from being published.
# noPublishedSources = true

# Uncomment this to disable Spotless checks.
disableSpotless = true

# Uncomment this to disable Checkstyle checks (currently wildcard import check).
disableCheckstyle = true

# Non-GTNH properties
org.gradle.configuration-cache = true
org.gradle.parallel = true

org.gradle.java.home=C:/Program Files/Eclipse Adoptium/jdk-25.0.4.101-hotspot

systemProp.javax.net.ssl.trustStoreType=Windows-ROOT

# 告诉 Gradle 去哪里找本地 JDK
org.gradle.java.installations.paths=C:/Program Files/Eclipse Adoptium/jdk-25.0.4.101-hotspot,C:/Program Files/Zulu/zulu-17,C:/Program Files/Zulu/zulu-21

# 禁用自动下载，避免再次因网络问题失败
org.gradle.java.installations.auto-download=false

gtnh.modules.gitVersion = false
modVersion = 1.0.0
